// AUTO-GENERATED by tools/generate-schedule.mjs — do not edit directly.
// Edit data/schedule.json, data/fallback.json, or data/invalidated.json,
// then run `npm run generate:schedule`.

import type { ScheduleEntry, WordEntry } from './schedule.js';

export const SCHEDULE_START_DATE = "2026-07-25";

export const SCHEDULE: ScheduleEntry[] = [
  {
    "date": "2026-07-25",
    "word": "TANGGAP",
    "definition": "to receive or accept something",
    "source": "https://en.wiktionary.org/wiki/tanggap",
    "difficulty": "easy"
  }
];

export const FALLBACK_POOL: WordEntry[] = [
  {
    "word": "TANGGOL",
    "definition": "to defend",
    "source": "https://en.wiktionary.org/wiki/tanggol",
    "difficulty": "easy"
  }
];

export const INVALIDATED_DATES: string[] = [];
